language: r
warnings_are_errors: true
sudo: required

r_github_packages:
  - smartinsightsfromdata/rpivotTable
  - trestletech/shinyAce
  - jeroenooms/jsonlite
  - rstudio/shiny
  - yihui/htmlwidgets@jsonlite
  - rstudio/DT
